# Generated by Django 4.2.3 on 2023-07-04 12:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0006_post_test_alter_post_content_alter_post_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='test',
        ),
    ]
