# Generated by Django 4.2.3 on 2023-07-07 17:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0011_post_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='image',
        ),
    ]
